cinema/cinema/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('movie.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cinema/movie/urls.py
from django.urls import path
from .views import *
from . import views


urlpatterns = [
    # path('single/', get_single),
    path('', Home.as_view(), name='home'),
    path('category/<str:slug>', MovieByCategory.as_view(), name='category'),
    path('genre/<str:slug>', MovieByGenre.as_view(), name='genre'),
    path('movie/<str:slug>', GetMovie.as_view(), name='movie'),
    path('review/<int:pk>', views.AddReview.as_view(), name='add_review'),
]

cinema/movie/models.py
from django.db import models
from datetime import date
from django.urls import reverse

class Category(models.Model):
    name = models.CharField("Категория", max_length=255)
    descripsion = models.TextField("Описание", blank=True)
    slug = models.SlugField(max_length=160, unique=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('category', kwargs={"slug": self.slug})

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"
        ordering =['name']

class Actor(models.Model):
    name = models.CharField("Имя актера", max_length=100)
    age = models.PositiveSmallIntegerField('Возраст', default=0)
    bio = models.TextField('Биография актера')
    photo = models.ImageField('Изображение', upload_to="actros/")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Актеры и режиссеры"
        verbose_name_plural = "Актеры и режиссеры"


class Genre(models.Model):
    name = models.CharField('Жанры', max_length=150)
    descripsion = models.TextField("Описание",)
    slug = models.SlugField(max_length=160, unique=True)


    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('genre', kwargs={"slug": self.slug})

    class Meta:
        verbose_name = "Жанр"
        verbose_name_plural = "Жанры"

class Movie(models.Model):
    title = models.CharField("Название фильмa", max_length=255)
    slogan = models.CharField("Слоган", max_length=100, default='')
    descripsion = models.TextField("Описание")
    poster = models.ImageField("Изображение", upload_to="movies/")
    year = models.PositiveSmallIntegerField("Дата выхода", default=2019)
    country = models.CharField('Страна', max_length=50)
    director = models.ManyToManyField(Actor, verbose_name="Режиссер", related_name='film_director')
    actors = models.ManyToManyField(Actor, verbose_name="Актеры", related_name="film_actor")
    genre = models.ManyToManyField(Genre, verbose_name="Жанры", related_name='movies')
    primer = models.DateField("Премьера в мире", default=date.today)
    budget = models.PositiveSmallIntegerField("Бюджет", default=0, help_text="Указать сумму в долларах")
    money_in_usa = models.PositiveSmallIntegerField("Сборы в США", default=0, help_text="Указать сумму в долларах")
    money_in_world = models.PositiveSmallIntegerField("Сборы в Мире", default=0, help_text="Указать сумму в долларах")
    category = models.ForeignKey(Category, verbose_name="Категория", on_delete=models.SET_NULL, null=True, related_name='movies')
    slug = models.SlugField(max_length=160, unique=True)
    is_published = models.BooleanField("Черновик", default=False)


    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('movie', kwargs={"slug": self.slug})

    def get_review(self):
        return self.reviews_set.filter(parent__isnull=True)


    class Meta:
        verbose_name = "Фильм"
        verbose_name_plural = "Фильмы"


class MovieShots(models.Model):
    title = models.CharField(max_length=150)
    descripsion = models.TextField(blank=True)
    image = models.ImageField("Изображение", upload_to="movie_shots/")
    movie = models.ForeignKey(Movie, verbose_name="Фильм", on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Кадр из фильма"
        verbose_name_plural = "Кадры и фильма"


class RatingStar(models.Model):
    value = models.PositiveSmallIntegerField("Значение", default=0)

    def __str__(self):
        return self.value

    class Meta:
        verbose_name = "Звезда рейтинга"
        verbose_name_plural = "Звезды рейтинга"


class Rating(models.Model):
    ip = models.CharField("Ip адрес", max_length=15)
    star = models.ForeignKey(RatingStar, verbose_name="Звезда", on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, verbose_name="Фильм", on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.star} - {self.movie}"

    class Meta:
        verbose_name = "Рейтинг"
        verbose_name_plural = "Рейтинги"

class Reviews(models.Model):
    email = models.EmailField()
    name = models.CharField("Имя", max_length=100)
    text = models.TextField("Сообщение", max_length=3000)
    parent = models.ForeignKey('self', verbose_name="Родитель", on_delete=models.SET_NULL, blank=True, null=True)
    movie = models.ForeignKey(Movie, verbose_name="Фильм", on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.name} - {self.movie}"

    class Meta:
        verbose_name = "Отзыв"
        verbose_name_plural = "Отзывы"

cinema/movie/forms.py
from django import forms

from .models import Reviews


class ReviewForm(forms.ModelForm):

    class Meta:
        model = Reviews
        fields = ('name', 'email', 'text')

cinema/movie/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView
from django.db.models import F
from django.views.generic.base import View

from .models import *
from .forms import ReviewForm

# def get_single(request):
#     movie = Movie.objects.all()
#     context = {
#         "movie": movie,
#         "title": 'Название фильма'
#     }
#     return render(request, template_name='single.html', context=context)


class Home(ListView):
    model = Movie
    template_name = 'index.html'
    context_object_name = 'movies'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Фильмы'
        return context


class MovieByCategory(ListView):
    template_name = 'index.html'
    context_object_name = 'movies'
    allow_empty = False

    def get_queryset(self):
        return Movie.objects.filter(category__slug=self.kwargs['slug'])

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['name'] = Category.objects.get(slug=self.kwargs['slug'])
        return context


class MovieByGenre(ListView):
    template_name = 'index.html'
    context_object_name = 'movies'
    allow_empty = False

    def get_queryset(self):
        return Movie.objects.filter(genre__slug=self.kwargs['slug'])

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['name'] = "Фильмы по жанрам" + str(Genre.objects.get(slug=self.kwargs['slug']))
        return context


class GetMovie(DetailView):
    model = Movie
    template_name = 'single.html'
    context_object_name = 'movie'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class AddReview(View):
    def post(self, request, pk):
        form = ReviewForm(request.POST)
        movie = Movie.objects.get(id=pk)
        if form.is_valid():
            form = form.save(commit=False)
            if request.POST.get("parent", None):
                form.parent_id = int(request.POST.get("parent"))
            form.movie = movie
            form.save()

        return redirect(movie.get_absolute_url())

cinema/movie/templates/index.html
{% extends 'base.html' %}
{% block content %}
<section class="ab-info-main py-md-5 py-4 editContent" style="padding-left: 3rem; padding-right: 3rem;">
        {% include 'inc/_sitebar.html' %}
                    <!-- //product left -->
                    <!-- product right -->
                    <div class="left-ads-display col-lg-9">
                        <div class="row">
                             {% for item in movies %}
                            <div class="col-md-4 product-men">
                                <div class="product-shoe-info editContent text-center mt-lg-4" >
                                    <div class="men-thumb-item">
                                        <img src="{{ item.poster.url }}" class="img-fluid" alt="" >
                                    </div>
                                    <div class="item-info-product">
                                        <h4 class="">
                                            <a href="{{ item.get_absolute_url }}" class="editContent" >{{ item.title }}</a>
                                        </h4>

                                        <div class="product_price">
                                            <div class="grid-price">
                                                <span class="money editContent" >{{ item.slogan }}</span>
                                            </div>
                                        </div>
                                        <ul class="stars">
                                            <li><a href="#"><span class="fa fa-star" aria-hidden="true" ></span></a></li>
                                            <li><a href="#"><span class="fa fa-star" aria-hidden="true" ></span></a></li>
                                            <li><a href="#"><span class="fa fa-star-half-o" aria-hidden="true" ></span></a></li>
                                            <li><a href="#"><span class="fa fa-star-half-o" aria-hidden="true" ></span></a></li>
                                            <li><a href="#"><span class="fa fa-star-o" aria-hidden="true" ></span></a></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                        <!--<div class="grid-img-right mt-4 text-right bg bg1" >
                            <span class="money editContent" >Flat 50% Off</span>
                            <a href="moviesingle.html" class="btn" >Now</a>
                        </div>-->
                    </div>
                </div>
            </div>
        </section>

{% endblock %}

cinema/movie/templates/single.html
{% extends 'base.html' %}
{% block content %}
    <section class="ab-info-main py-md-5 py-4 editContent"
             style="outline: none; outline-offset: -2px; cursor: inherit; color: rgb(33, 37, 41); font-size: 16px; background-color: rgba(0, 0, 0, 0); font-family: Lato, sans-serif;">
        <div class="container py-md-3">
            <!-- top Products -->
            <div class="row">
                <!-- product left -->
                {% include 'inc/_sitebar.html' %}
                <!-- //product left -->
                <!-- product right -->
                <div class="left-ads-display col-lg-8">
                    <div class="row">
                        <div class="desc1-left col-md-6">
                            <img src="{{ movie.poster.url }}" class="img-fluid" alt="">
                        </div>
                        <div class="desc1-right col-md-6 pl-lg-4">
                            <h3 class="editContent" style="outline: none; cursor: inherit;">
                                {{ movie.title }}</h3>
                            <h5 class="editContent">{{movie.title}}</h5>
                            <ul>
                                <li style="list-style: none"><span><b>Год:</b>{{ movie.year }}</span></li>
                                <li style="list-style: none"><span><b>Страна:</b>{{ movie.country }}</span>
                                </li>
                                <li style="list-style: none"><span><b>Слоган:</b>{{ movie.slogan }}</span>
                                </li>
                                <li style="list-style: none">
                                    <span><b>Режиссер:</b>
                                        {% for item in movie.director.all %}
                                    <a href="{{item.get_absolute_url}}">{{ item.name }}</a>
                                    {% endfor %}
                                    </span></li>
                                <li style="list-style: none"><span><b>Актеры:</b>
                                {% for item in movie.actors.all %}
                                    <a href="{{item.get_absolute_url}}">{{ item.name }}</a>
                                    {% endfor %}
                                </span></li>
                                <li style="list-style: none"><span><b>Жанр:</b>
                                    {% for item in movie.genre.all %}
                                    <a href="{{item.get_absolute_url}}">{{ item.name }}  </a>
                                    {% endfor %}
                                </span>
                                </li>
                                <li style="list-style: none"><span><b>Премьера в мире:</b>{{ movie.primer }}</span>
                                </li>
                                <li style="list-style: none">
                                    <span><b>Бюджет:</b>{{ movie.budget }}</span></li>
                                <li style="list-style: none">
                                    <span><b>Сборы в США:</b> ${{ movie.money_in_usa }}</span></li>
                                <li style="list-style: none"><span><b>Сборы в мире:</b> ${{ movie.money_in_world }}</span>
                                </li>
                                <li style="list-style: none">
                                    <a href="#"><b>Рейтинг:</b>
                                    <span class="fa fa-star" aria-hidden="true"
                                          style="outline: none; cursor: inherit;"></span>
                                        <span class="fa fa-star" aria-hidden="true"
                                              style="outline: none; cursor: inherit;"></span>
                                        <span class="fa fa-star" aria-hidden="true"
                                              style="outline: none; cursor: inherit;"></span>
                                        <span class="fa fa-star" aria-hidden="true"
                                              style="outline: none; cursor: inherit;"></span>
                                        <span class="fa fa-star" aria-hidden="true"
                                              style="outline: none; cursor: inherit;"></span>
                                        <span class="editContent"
                                              style="outline: none; cursor: inherit;">5.0</span>
                                    </a>
                                </li>
                                <div class="share-desc">
                                    <div class="share">
                                        <h4 class="editContent"
                                            style="outline: none; cursor: inherit;">
                                            Share:</h4>
                                        <ul class="w3layouts_social_list list-unstyled">
                                            <li>
                                                <a href="#" class="w3pvt_facebook editContent"
                                                   style="outline: none; cursor: inherit;">
                                                <span class="fa fa-facebook-f"
                                                      style="outline: none; cursor: inherit;"></span>
                                                </a>
                                            </li>
                                            <li>
                                                <a href="#" class="w3pvt_twitter editContent"
                                                   style="outline: none; cursor: inherit;">
                                                <span class="fa fa-twitter"
                                                      style="outline: none; cursor: inherit;"></span>
                                                </a>
                                            </li>
                                            <li>
                                                <a href="#" class="w3pvt_dribble editContent"
                                                   style="outline: none; cursor: inherit;">
                                                <span class="fa fa-dribbble"
                                                      style="outline: none; cursor: inherit;"></span>
                                                </a>
                                            </li>
                                        </ul>
                                    </div>
                                    <div class="clearfix"></div>
                                </div>
                        </div>
                    </div>
                    <div class="row sub-para-w3layouts mt-5">

                        <h3 class="shop-sing editContent" style="outline: none; cursor: inherit;">
                            О фильме {{ movie.title }}</h3>
                        <p>
                            {% for image in movie.movieshots_set.all %}
                             <img src="{{ image.image.url }}" class="img-fluid" alt="{{ image.name }}" width="250">

                            {% endfor %}
                        </p>
                        <p class="editContent" style="outline: none; cursor: inherit;"> {{ movie.descripsion }}</p>
                        <p class="mt-3 italic-blue editContent"
                           style="outline: none; cursor: inherit;">
                            <iframe width="560" height="315" src="https://www.youtube.com/embed/ZOTTyJz80w8" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                        </p>
                        <p class="mt-3 editContent" style="outline: none; cursor: inherit;">
                        </p>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="single-form-left">
                            <!-- contact form grid -->
                            <div class="contact-single">
                                <h3 class="editContent" style="outline: none; cursor: inherit;">
                                    <span class="sub-tittle editContent"
                                          style="outline: none; cursor: inherit;"></span>Оставить отзыв</h3>
                                <form action="{% url 'add_review' movie.id %}" method="post" class="mt-4" id="formReview">
                                        {% csrf_token %}
                                    <input type="hidden" name="parent" id="contactparent" value="">
                                    <div class="form-group editContent"
                                         style="outline: none; cursor: inherit;">
                                        <label for="contactcomment" class="editContent"
                                               style="outline: none; cursor: inherit;">Ваш комментарий
                                            *</label>
                                        <textarea class="form-control border" rows="5" name="text"
                                                  id="contactcomment" required=""></textarea>
                                    </div>
                                    <div class="d-sm-flex">
                                        <div class="col-sm-6 form-group p-0 editContent"
                                             style="outline: none; cursor: inherit;">
                                            <label for="contactusername" class="editContent"
                                                   style="outline: none; cursor: inherit;">Имя
                                                *</label>
                                            <input type="text" class="form-control border" name="name"
                                                   id="contactusername" required="">
                                        </div>
                                        <div class="col-sm-6 form-group ml-sm-3 editContent"
                                             style="outline: none; cursor: inherit;">
                                            <label for="contactemail" class="editContent"
                                                   style="outline: none; cursor: inherit;">Email
                                                *</label>
                                            <input type="email" class="form-control border" name="email"
                                                   id="contactemail" required="">
                                        </div>
                                    </div>
                                    <button type="submit"
                                            class="mt-3 btn btn-success btn-block py-3"
                                            style="outline: none; cursor: inherit;">Отправить
                                    </button>
                                </form>
                            </div>
                            <!--  //contact form grid ends here -->
                        </div>
                    </div>
                    <div>
                        {% for review in movie.get_review %}
                        <div class="media py-5">
                            <img src="https://vsegda-pomnim.com/uploads/posts/2022-04/1649232810_60-vsegda-pomnim-com-p-pustoe-litso-foto-79.jpg" class="mr-3 img-fluid"  width="50px" alt="image"
                                 style="outline: none; cursor: inherit;">
                            <div class="media-body mt-4">
                                <h5 class="mt-0 editContent"
                                    style="outline: none; cursor: inherit;">{{ review.name }}</h5>
                                <p class="mt-2 editContent" style="outline: none; cursor: inherit;">
                                    {{ review.text }}
                                </p>
                                <a href="#formReview" onclick="addReview('{{ review.name }}', '{{ review.id }}')">Ответить</a>

                                {% for rev in review.reviews_set.all  %}
                                <div class="media mt-5 editContent"
                                     style="outline: none; cursor: inherit;">
                                    <a class="pr-3" href="#">
                                        <img src="https://vsegda-pomnim.com/uploads/posts/2022-04/1649232810_60-vsegda-pomnim-com-p-pustoe-litso-foto-79.jpg" class="img-fluid" width="50px" alt="image" style="outline: none; cursor: inherit;">
                                    </a>
                                    <div class="media-body">
                                        <h5 class="mt-0 editContent"
                                            style="outline: none; cursor: inherit;">{{ rev.name }}</h5>
                                        <p class="mt-2 editContent"
                                           style="outline: none; cursor: inherit;">{{ rev.text }} </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                            {% endfor %}
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </section>
<script>
    function addReview(name, id) {
        document.getElementById("contactparent").value = id;
        document.getElementById("contactcomment").innerText = name,
    }
</script>
{% endblock %}

cinema/movie/templates/tags/get_genries.html
{% for item in genre %}
<li class="editContent" >
    <a href="{{item.get_absolute_url}}">{{ item.name }}</a>
</li>
{% endfor %}

cinema/movie/templates/tags/get_menu.html
{% load get_genries %}
<li>
    <!-- First Tier Drop Down -->
    {% for item in categories %}
    <label for="drop-2" class="toggle"> {{ item.name }}<span class="fa fa-angle-down" aria-hidden="true" ></span> </label>
    <a href="{{ item.get_absolute_url }}">{{ item.name }} <span class="fa fa-angle-down" aria-hidden="true"></span></a>
    {% endfor %}
    <input type="checkbox" id="drop-2">
    <ul>
        {% show_genries %}
    </ul>
</li>

cinema/movie/templates/tags/show_last_movies.html
{% for item in movies %}
<div class="special-sec1 row mt-3 editContent" >
    <div class="img-deals col-md-4">
        <a href="{{ item.get_absolute_url }}"><img src="{{ item.poster.url }}" class="img-fluid" alt="" ></a>
    </div>
    <div class="img-deal1 col-md-8">
        <a href="{{ item.get_absolute_url }}" class="editContent" >
        <h3 class="editContent" >{{ item.title }}</h3>
        </a>
    </div>
</div>
{% endfor %}

cinema/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <!-- //Meta tag Keywords -->
    <title>CinemaEl</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- //Meta tag Keywords -->
    <!-- Custom-Files -->
    <link rel="stylesheet" href="{% static './css/bootstrap.css' %}">
    <!-- Bootstrap-Core-CSS -->
    <!--/ Style-CSS -->
    <link rel="stylesheet" href="{% static './css/style.css' %}" type="text/css" media="all">
    <!--// Style-CSS -->
    <!-- font-awesome-icons -->
    <link href="{% static './css/font-awesome.css' %}" rel="stylesheet">
    <!-- //font-awesome-icons -->
  <!-- /Fonts -->
    <link href="//fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700" rel="stylesheet">
    <link href="//fonts.googleapis.com/css?family=Source+Sans+Pro:200,200i,300,300i,400,400i,600,600i,700,700i,900" rel="stylesheet">
    <!-- //Fonts -->
</head>

<body>

    <div id="page" class="page"><!-- mian-content -->
        {% include 'inc/_header.html' %}

        {% block content %} {% endblock %}

        {% include 'inc/_footer.html' %}
    </div>
</body>
</html>

cinema/templates/inc/_header.html
{% load get_menu %}
        <div class="main-banner bg bg1" id="home" style="background-color: rgba(0, 0, 0, 0); margin-top: 0px; background-image: url(&quot;https://images4.alphacoders.com/119/1194463.jpg&quot;);">
            <!-- header -->
            <header class="header">
                <div class="container-fluid px-lg-5">
                    <!-- nav -->
                    <nav class="py-4">
                        <div id="logo">
                            <h1> <a href="{% url 'home' %}" class="active" style="outline: none; outline-offset: -2px; cursor: inherit; color: rgb(255, 255, 255); font-size: 40px; background-color: rgba(0, 0, 0, 0); font-family: &quot;Source Sans Pro&quot;, sans-serif;">CinemaEl</a></h1>
                        </div>

                        <label for="drop" class="toggle">Menu</label>
                        <input type="checkbox" id="drop">
                        <ul class="menu mt-2">
                            <li class="active"><a href="{% url 'home' %}">Главная</a></li>
                                {% show_menu %}
                            <li><a href="contact.html" style="color: rgb(255, 255, 255); font-weight: 700; text-transform: uppercase;">Вход</a></li>
                        </ul>
                    </nav>
                    <!-- //nav -->
                </div>
            </header>
            <!-- //header -->
            <!--/banner-->
            <div class="banner-info">
                <p class="editContent" >Я только учусь</p>
                <h3 class="mb-4 editContent">Все о кино</h3>
                <div class="ban-buttons">


                </div>
            </div>
            <!--// banner-inner -->
        </div>
        <!--//main-content-->
        <!---->